# Generated by Django 3.2.9 on 2021-11-07 12:07

from django.db import migrations, models
import projectApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectApp', '0002_alter_imagedata_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagedata',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=projectApp.models.upload_path),
        ),
    ]
